In [2]:
# ============================================================
# IMPORT LIBRARIES
# ============================================================

import io
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries imported successfully.")

Libraries imported successfully.

In [ ]:
# df = pd.read_excel("students-list-2026-all-class-all-section.xlsx")
df = pd.read_excel("class_10_single_sheet_automated_result.xlsx")
dfstudents-list-2026-all-class-all-section.xlsx

,RAHIMA FIRUJ SIKDER HIGH SCHOOL — CLASS TEN RESULT SHEET,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54
0,Exam: MODEL TEST 2026 | Academic Year: 2026 ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Enter marks from 0–100 in each subject. Type A...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Roll,Student Name,Section,Group,Registration No.,BANGLA Marks,BANGLA Grade,ENGLISH Marks,ENGLISH Grade,Mathematics Marks,...,Business Entrepreneurship Marks,Business Entrepreneurship Grade,Agriculture Studies Marks,Agriculture Studies Grade,Accounting Marks,Accounting Grade,Total Marks,Subjects Entered,CGPA,Final Result
3,1,KAZI TANJINA BEGUM,A,NaN,NaN,NaN,NaN,57,NaN,42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2,MST SOHEDA AKTHER SADIYA,A,NaN,NaN,NaN,NaN,40.5,NaN,31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,105,SOHANUR RAHMAN SOHAG,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107,107,IFAT MIAH,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
108,109,KHELA BEGUM,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,110,SAHJAT AHMED SOJIB,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110,111,NAIMA BEGUM,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
import tabula

# dfs = tabula.read_pdf("SSC Model Test Result Tabulation_Ten2026.pdf", pages="all")

# dfs

df = tabula.io.read_pdf("SSC Model Test Result Tabulation_Ten2026.pdf", pages="all")
df[0]

Got stderr: Oct 13, 2026 10:42:56 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font LiberationSans for base font Symbol
Oct 13, 2026 10:42:56 PM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font LiberationSans for base font ZapfDingbats

,Exam Mark Head,English 1st Paper,English 2nd Paper,Mathematics,Geography &,Unnamed: 0,Science,Physics,Chemistry ClasOsv: eTreanll (A)
0,NaN,NaN,NaN,Tabulation Sheet,environment,NaN,NaN,NaN,Year: 2026
1,"1. KAZI TANJINA BEGUM, Father: KAZI SUBA MIAH,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,MODEL TEST CQ,73,41 Rahima Firuj Sikder High School,34,58,NaN,45,-,T- otal: 38 | Pass: 5F |( F1a) il: 33MODEL TE...
3,2E0x2a6m... Mark Head,English 1st Paper,English 2nd Paper,Mathematics,Geography &,NaN,Science,Physics,Chemistry ClasOsv: eTreanll (A)
4,MCQ,-,-,Tabula8tion Sheet,enviro1n9ment,NaN,18,-,- Ye0a.0r:0 2026
5,"1. KAZI TANJINA BEGUM, Father: KAZI SUBA MIAH,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,MODEL TEST PRACTQICAL,7-3,4-1Rahima Firuj S3-4ikder High School,NaN,5-8,NaN,4-5,-,T- otal: 38 | Pass:2 5F9 6|( F1.0a)0il: 33MOD...
7,2E0x2a6m... Mark Head,English 1st Paper,English 2nd Paper,Mathematics,Geography &,NaN,Science,Physics,Chemistry ClasOsv: eTreanll (A)
8,TMOTCAQL,"73 (A,- 4.00)","41 (B,- 3.00)","Tab42u (lFa,8 0ti.0o0n) Sheet","e7n7v i(rAo1,n9 4m.0e0n) t",NaN,"63 (A1-,8 3.50)","- (--, -)","- (--, -) 0.00"

In [19]:
import re  # Only needed if using regex patterns
import pandas as pd

df_students = pd.read_excel(
    "students-list-2026-all-class-all-section.xlsx", sheet_name="Worksheet"
)
df_ten = df_students[df_students["Class"].str.lower() == "ten"].copy()
print(f"Total Class Ten students in Excel: {len(df_ten)}")
print(df_ten[["Roll", "Name", "Section", "Class"]].to_string())

Total Class Ten students in Excel: 108
     Roll                       Name Section Class
1       1         KAZI TANJINA BEGUM       A   Ten
7       2   MST SOHEDA AKTHER SADIYA       A   Ten
12      3          SAMIRA YASMIN EMA       A   Ten
17      4         SAIDA AFRIN PAPIYA       A   Ten
22      5          MST SAMIYA AKTHER       A   Ten
27      6         MST KHADIJA AKTHER       A   Ten
34      7        RAHIMA AKTHER MUNNI       A   Ten
37      8  KAZI LOTIFA AKTER TANJINA       A   Ten
42      9                NAIMA BEGUM       A   Ten
47     10               SUMONA BEGUM       A   Ten
52     11  KAZI FARJANA AKTER TANIYA       A   Ten
57     12           LIZA AKTHER LIMA       A   Ten
62     13   MST AFSANA JANNAT SAMIRA       A   Ten
67     14              TAHMINA BEGUM       A   Ten
71     15               HAMIDA BEGUM       A   Ten
76     16             MADIHA SULTANA       A   Ten
81     17              HABIBA  BEGUM       A   Ten
86     18          MST KHADIJA BEGUM       A   Ten
95     20            CHAITI RANI DAS       A   Ten
99     21             TASLIMA AKTHER       A   Ten
103    22      SHAHRIYA JANNAT TARIN       A   Ten
111    24               Nahida Begum       A   Ten
114    25                MUNNI BEGUM       A   Ten
119    26   ANONNYA SUTRADHAR CHAITY       A   Ten
124    27        KHADIJA JANNAT URMI       A   Ten
129    28         SAMIRA AKTHER RIYA       A   Ten
134    29        TAJIBA NUSRAT TAJIN       A   Ten
139    30      MST HAJERA AKTER KOLI       A   Ten
143    31               SUMONA BEGUM       A   Ten
150    33          SHAH SARMIN BEGUM       A   Ten
154    34         NADIYA YASMIN URMI       A   Ten
168    38      MUDABBIR UDDIN SIKDER       A   Ten
172    39       MAHIRA JANNAT SADIYA       A   Ten
182    42        TAHIYA AKTAR SADIYA       A   Ten
186    43              TAMANNA BEGUM       A   Ten
190    44      MST AKLIMA BEGUM SONY       A   Ten
194    45      MST JUHRA EMAMA TAIFA       A   Ten
198    46               SADIA JANNAT       A   Ten
237    19                EMON HUSSEN       B   Ten
238    23               RAZZAK HUSEN       B   Ten
239    32           ROBIN AHMED SAIM       B   Ten
240    35                LOKHON MIAH       B   Ten
241    36            MD RAHMAN HUSEN       B   Ten
242    37          TAMIM AHMED SOJID       B   Ten
243    40   MUHAIMIN CHOWDHURY MAHDI       B   Ten
244    41    MD MAHBUBUL HASAN TAMIM       B   Ten
245    47         HRIDOY HASAN TAMIM       B   Ten
246    48          SHAH SAMIYA AKTER       B   Ten
247    49               MD NIHAD ALI       B   Ten
248    50     TAYYIBA  NUSRAT  TARIN       B   Ten
249    51               SAMIYA BEGUM       B   Ten
250    52                SAKIB AHMED       B   Ten
251    53      KAWSAR AHMED MUHABIYA       B   Ten
252    54      MUDASSIR UDDIN SIKDER       B   Ten
253    55           FARHAN CHOWDHURY       B   Ten
254    57         NADIRA AKTHER RITA       B   Ten
255    58           MOHI UDDIN JIHAD       B   Ten
256    59         SAMIRA AKTHER LIMA       B   Ten
257    60   MST TAHMIDA JANNAT TAMMI       B   Ten
258    61               SADIYA BEGUM       B   Ten
259    62   MST FATEMA AKTHER MAHIMA       B   Ten
260    63        SHEIKH TAIBA JANNAT       B   Ten
261    64           RAHIMA AKTER EMA       B   Ten
262    65      MD TAHINUL ISLAM RAHI       B   Ten
263    66    MST HUMAIRA BEGUM TANIA       B   Ten
264    67          SANJEDA AKTER EMU       B   Ten
265    68            MD KAWSAR AHMED       B   Ten
266    69      SUMAIYA AKTHER SADIYA       B   Ten
267    70               MD SAJU MIAH       B   Ten
268    72     MD AMDADUL ISLAM SAYEM       B   Ten
269    73         RUHINA YASMIN RINI       B   Ten
270    74               HAMIDA BEGUM       B   Ten
271    75               TAMVIR AHMED       B   Ten
272    76                 AMAD AHMED       B   Ten
273    77           MST NADIYA BEGUM       B   Ten
274    78                SAYMA BEGUM       B   Ten
275    79               SERWAN AHMED       B   Ten
276    80                 MUNSUR ALI       B   Ten
277    81               LILIMA BEGUM       B   Ten
278    82         JAIDUL ISLAM NAHID       B   Ten
279    83                 RITA BEGUM       B   Ten
280    84            MST AYSHA BEGUM       B   Ten
281    85         KAZI THALHA  AHMED       B   Ten
282    86               SAMIYA AKTAR       B   Ten
283    87   MST TAMIMA JANNAT TAHIYA       B   Ten
284    88                 MD. SALMAN       B   Ten
285    89         MST SANJIDA AKTHER       B   Ten
286    90  Mst . Rahima Akter Sadiya       B   Ten
287    91                  EMA BEGUM       B   Ten
288    92             MD RABBI AHMED       B   Ten
289    93              MD LAEIN MIAH       B   Ten
290    94            MD SHAHED AHMED       B   Ten
291    95             MD MAHID AHMED       B   Ten
292    96                 RAHID MIAH       B   Ten
293    97        AZHARUL ISLAM SUHAG       B   Ten
294    98      FAHIMA JANNAT TAMANNA       B   Ten
295    99       ABDULLAH HASAN SAKIB       B   Ten
296    99       FAHMIDA AKTHER ANIKA       B   Ten
297   100               HUSAIN AHMED       B   Ten
298   102                NUMAN AHMED       B   Ten
299   103            MD KAMRUL ISLAM       B   Ten
300   104         HASAN MAHMUD TAMIM       B   Ten
301   105          MST BUSHRA KHANOM       B   Ten
302   105       SOHANUR RAHMAN SOHAG       B   Ten
303   107                  IFAT MIAH       B   Ten
304   109                KHELA BEGUM       B   Ten
305   110         SAHJAT AHMED SOJIB       B   Ten
306   111                NAIMA BEGUM       B   Ten